### ISSUE TITLE
CMake did not find 'glog'

### ISSUE THREAD

**Issue by bigbigpark** [pierdell/viz3d#7]
~~~bash
[VIZ3D] -- Generating CMake File
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at cmake/external.cmake:8 (find_package):
  By not providing "Findglog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "glog", but
  CMake did not find one.

  Could not find a package configuration file provided by "glog" with any of
  the following names:

    glogConfig.cmake
    glog-config.cmake

  Add the installation prefix of "glog" to CMAKE_PREFIX_PATH or set
  "glog_DIR" to a directory containing one of the above files.  If "glog"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:11 (include)


-- Configuring incomplete, errors occurred!
See also "/home/scpark/tools/viz3d/cmake-build-Release/CMakeFiles/CMakeOutput.log".
[VIZ3D] Failure. Exiting.
~~~

I git cloned 'viz3d_old' branch and run `./install.sh`. <br/>
Upper errors occur <br/>
How can I fix them? <br/>

<br/>

Thanks, best regards <br/>

**Comment by pdell-kitware** [comment]
Hi, 

So I revived recently this old branch, apparently I had some problem with the specification of the default path to the cmake config-file of the dependencies, 

I attempted to fix it in branch [`viz3d_old_fix`](https://github.com/pierdell/viz3d/tree/viz3d_old_fix), can you try on this branch ?

Essentially you need to specify `glog_DIR` variable before calling find_package, instead of GLOG_DIR as in this commit, 

If this the branch does not solve your issue, could you give me the relative path to the glog-config.cmake 
(with respect to the cloned directory ?)

**Comment by bigbigpark** [comment]
Thanks for replying. Here are my absolute path 

![image](https://user-images.githubusercontent.com/72936863/161881938-a6d55d46-4ebb-4688-bdf8-ed45653d7d6e.png)

<br/>

Or, when I type this `$ dpkg -L libgoogle-glog-dev`, <br/>
It says <br/>

~~~bash
/.
/usr
/usr/include
/usr/include/glog
/usr/include/glog/log_severity.h
/usr/include/glog/logging.h
/usr/include/glog/raw_logging.h
/usr/include/glog/stl_logging.h
/usr/include/glog/vlog_is_on.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libglog.a
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/libglog.pc
/usr/share
/usr/share/doc
/usr/share/doc/libgoogle-glog-dev
/usr/share/doc/libgoogle-glog-dev/copyright
/usr/lib/x86_64-linux-gnu/libglog.so
/usr/share/doc/libgoogle-glog-dev/changelog.Debian.gz
~~~

**Comment by pdell-kitware** [comment]
So have you tried the branch `viz3d_old_fix`, it should set glog_DIR to the right directory ? 

Before calling install.sh you should erase the CMakeCache.txt  of the Superbuild, which should be at cmake-build-Release/external)


Explanation:

What you need is for the CMake to find the package glog *installed by the Superbuild*, 
The install directory is /home/cspark/tools/viz3d/install/glog, so you should verify that the glog_DIR CMake variable (in cmake/external.cmake script) equals `/home/cspark/tools/viz3d/install/glog/lib/cmake/glog`

**Comment by bigbigpark** [comment]
Thanks you so much <br/>
I built viz3d package successfully for your help :) <br/>
